controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 37
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
route:
  app:
    hostnames:
      - echo.bubsybox.dev
    parentRefs:
      - name: external
        namespace: kube-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8080
sops:
  age:
    - recipient: age1wvmqsclxt9s2xaqc0rarsyp5d76jg4rh5zawterhkzjm2wvz8uxswff94q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMXhjVk1Ya1ZHaExpaDBS
        K3JnWWUxOUR1V1k0ZWlTWTZhRUExNHB4emdJCmpUM1R0dGdzOTlQeVp5Uk1DcHZz
        NEN3bFNYRDkvVjBjcDZJWXBEQW5QZEUKLS0tIHhaTWdQZGdXSHJVYWtIOHJidVVr
        YnZvbU9aYnA3aHBDYjJESmFkY21rMFkK+p40syB8eRIpPuaBwgm+cR+jwazpV2mJ
        ikLT1GKHCVm084puHmaGhB7b9spOFWh3MPGJfKUEVJwptnDDp6fhCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-01T18:35:38Z"
  mac: ENC[AES256_GCM,data:0zSciPgGc3Kevl0jFQuPEIAQ5ApF3R98ysvr02PaZSstq+FGWF8JgmhJ1Sr4+JezS3/9nSC/OrquT+dtfYafUEbVCwpcjiFDQMOkWptWdDL7OW/AQytIVQ8oADL1gZTuPj2CNL51ntwM23NoyZWbGdfZsuqb8FVqO+apdMvgQrQ=,iv:9v0Fh1ZV+wj7wHjqdXE6XIebAaJ6u/8+FhK9BahbvrY=,tag:SUQ8Meb102auAI/ba2Y/VA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
