fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - bubsybox.dev
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - recipient: age1wvmqsclxt9s2xaqc0rarsyp5d76jg4rh5zawterhkzjm2wvz8uxswff94q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzKzhweU4rdU1PZXM4Wk5L
        cklld1lJQW9uMlZvZ240YTFYeldkYUQ2SkJBCkZZQWswdnpIcVlUWUxVQjQyUFl5
        RStsRkhFRForK2tNZW1YWjUzRXJNcmcKLS0tIFFEWThYTWtVeWZ4Q3ZibEl4L0pt
        QUdKY0pTZ0Jhb09JZ20rU2FoTjBKMEEK0oWAVE5K1Tt1wDNyf3+5s5fNjaykcZ9h
        4KNpbnxBqU5HABXnBnIsnn3CWzvUHeCI3/NTYgiga1T4XREk3EiP6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-01T19:39:55Z"
  mac: ENC[AES256_GCM,data:37PLIiMvzrI03JS2Ctml98NsNtwySlM1b0LQ9PRhiJNzlkc2RdL94xVukZhPcK2a7Q87TVNnn4fFiin65ljnTZ8h6TGgeOHtPnpf7QcZtt+BEZJsPoeQH76z4kNfAnk/Ie+9q6ZfVra9WaBIMixEyNQJ+VhUZmtZFtl+2+4MSuc=,iv:W4ijfMu5rd1j4fh/adVPncvlBA46/90XTKzCjXRxJBQ=,tag:W8NeLSVXBinGSOvN4JvXew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
