# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:c0KD,iv:musv0midWaAAONUNAHINMKanX1wZ63RHG4bVYimMF0w=,tag:lqUXUGwN2HwYBOvQqNlAOA==,type:str]
  url: ENC[AES256_GCM,data:jMVsqgocQX9AC6Dwwe/euGS5DLF3O5pDgQDHoXRre01zaK8AJcTQKzHDNvbKDy4=,iv:pNTXjlDpkDfTEIXC6BjHxxm+p1EdVzxaXJ9y6YGYuiA=,tag:M00wj0YxGgysqEpbmUg/kg==,type:str]
sops:
  age:
    - recipient: age1wvmqsclxt9s2xaqc0rarsyp5d76jg4rh5zawterhkzjm2wvz8uxswff94q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MWRyUHBGMVRTOURxWE5x
        SkZTMTNqeCtybEl4emh6UGY5Nm9jNjRYdFM0CktNbjF5UFBqaTROMlJyMGZmdnJH
        Q2VOdE5MYUNWZ1ZHZlpTR2d0VExnc28KLS0tIDdWaUE3ZzNhWkpzVXNwODY0UzJN
        SWhJYmFiRDEyaXZqNWRGWkt6TmdqSWsKiPA3TtNZez+Gbhizh40QFQz1sQTDvt/G
        OxEyStDYa8DW45OWmbOCpQw1T8i37d0VnNqnItTDhc4h8RFfRsZ2pQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-01T18:35:39Z"
  mac: ENC[AES256_GCM,data:6mYw6FwqQ6VT/oJBVPiWmJOry5i7xtB7/UPg0YuAlJ3o0UtMJPfQ+i2bRa1wekvteqnRoeKq1dBxc/kgdGTYPl2GrLWgm/lkQC32K9J+RWc6qU2TjUwYiGdeM7lbb8ltLyp529/Pc8rpzIupg6wXZ2lU29elXJixs0uJcTfEMiM=,iv:g4+yMHlasd7tSMhJRCl7UvOOYGLhPd9TqOlJPKIe+WY=,tag:6WNBSk39PmNxrh2uyEak9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
