# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - bubsybox.dev
sops:
  age:
    - recipient: age1wvmqsclxt9s2xaqc0rarsyp5d76jg4rh5zawterhkzjm2wvz8uxswff94q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZkFGUTdFLzhoVDd4cThK
        REFjaXJDMjVRWFlORVk2R1l2TVJKUGpnWmxFCngrZmhBTDFjVk0zd0NoMkVnYzVi
        cWNoNVJFZU5sNXJtUjhENTdGS1NlR0UKLS0tICtOd2liVHBGaE8wT0R1L0pzU1ZY
        MUZUa1J2ekxLblpSSGEvcnZsWU9ZOWMKT4WjZ5F9gpQ949fBiKF6rdRSNLA6VNBK
        Tn3T3mTyPlLc+JtwoF90W+lvNRoS0SHDWOCOowvrs9VdhYO93Ih5ZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-01T18:35:38Z"
  mac: ENC[AES256_GCM,data:p5tDExjl+/Qa1xZCAx01/5ux7jTA1Nn7mYYFRP8cJ27LRH1N0r/uQu73YRSLhofs2clufR7fH30LSdZlhu/aDK7vUnHupUL62SOQsTMSW+2cAIdktr5v/QvGxcOp+iRiRY5L4Yv9afeMbwCVo23IoY8+234HU1E/wPePhErT2jg=,iv:C+X1muhWYqqsddjNiFOjSYHT0842GOQTcCc9SIL1lyE=,tag:4fgNI7NkzaT8rmmTgeLbPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
