# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:6KloEbS8uQsKxgvnz/DoGJgi7bU86VuVMxBe7oyypW6CJjdInD3h6A==,iv:XlP26y2ODYY34gR6cwPSdO6sxxQxOIDeTqfjYNRjSU4=,tag:U37zTfmQFQTNftQKrcwVcA==,type:str]
sops:
  age:
    - recipient: age1wvmqsclxt9s2xaqc0rarsyp5d76jg4rh5zawterhkzjm2wvz8uxswff94q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcERsdlhkRTAxZnF4eTV3
        aVg2SkRkU040Z0xzUllmbjlnM04vVUF5Qnk4CkI3cWcrVXlXQWlpTU5pU0ZzMWta
        cE83SXZKMnZ5ZVNwVm9EQllhME1QQjgKLS0tIG14aFpJWFBuVmZqUG5aQXVDVnpD
        YzBmaDNqZDBBN0JJSmxkL3g0THhVZTgK/XcS9BTcmgRn7hybBhJ3tS/V6CzzYgYB
        P0Wdbj1iVt1i7TNcGd/IN3WzC5im/Qc2EebmsXT+Awhd9SV34neRkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-01T19:39:54Z"
  mac: ENC[AES256_GCM,data:zUEbEbCEyMm38E3drH6jU1JPkNQUfUq0M9tS2O2sf5+XvBomg0bTQXP+N18FLCFsR6tjF5jYvxe4TemjcwnEa2kYaNIAKHImxD7fB1UTaR9IGlZMIbK+4THFuIQ7OoUJt1Mm5x2/h4Av3SRLAMod51L3q1rGwkSuhTTFeqkfqRU=,iv:hRk6qCqWnrXvcDrbbBwJqvwPMwJyFgQBcHRtPDry6os=,tag:JQkidGh3Rp3x45/2l1Ylfw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
