# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.99.99:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.99.99"
  - "talos.bubsybox.internal"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "tikka"
    ipAddress: "10.0.99.30"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:cb:5c:b4"
        dhcp: false
        addresses:
          - "10.0.99.30/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.99.1"
        mtu: 1500
        vip:
          ip: "10.0.99.99"
  - hostname: "lassi"
    ipAddress: "10.0.99.35"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:68:40:66"
        dhcp: false
        addresses:
          - "10.0.99.35/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.99.1"
        mtu: 1500
        vip:
          ip: "10.0.99.99"
  - hostname: "gobi"
    ipAddress: "10.0.99.40"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:b5:df:e2"
        dhcp: false
        addresses:
          - "10.0.99.40/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.99.1"
        mtu: 1500
        vip:
          ip: "10.0.99.99"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

